package com.dnyaneshwar.bank.repository;

import com.dnyaneshwar.bank.entity.Account;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Lock;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import jakarta.persistence.LockModeType;

import java.util.Optional;

/**
 * Repository for Account entity.
 *
 * JpaRepository provides built-in CRUD operations:
 * - save()
 * - findById()
 * - findAll()
 * - deleteById()
 * - etc.
 */
public interface AccountRepository extends JpaRepository<Account, Long> {

    /**
     * Find an account using the account number.
     *
     * Use this method for READ operations only.
     *
     * Examples:
     * - Check account balance
     * - View account details
     * - Display account information
     *
     * No database lock is applied.
     * Multiple users can read the same account simultaneously.
     */
    Optional<Account> findByAccountNumber(String accountNumber);


    /**
     * Check whether an account number already exists.
     *
     * Used while creating a new account to ensure
     * that duplicate account numbers are not generated.
     *
     * Returns:
     * true  -> account exists
     * false -> account does not exist
     */
    boolean existsByAccountNumber(String accountNumber);


    /**
     * Find an account and lock the database row.
     *
     * PESSIMISTIC_WRITE places a database lock on the row
     * until the current transaction completes.
     *
     * This prevents two users from updating the same account
     * balance at the same time.
     *
     * Use ONLY for money-changing operations:
     * - Deposit
     * - Withdraw
     * - Transfer
     *
     * SQL generated by Hibernate is similar to:
     *
     * SELECT * FROM accounts
     * WHERE account_number = ?
     * FOR UPDATE;
     *
     * IMPORTANT:
     * This method must always be called inside a
     * @Transactional service method.
     */
    @Lock(LockModeType.PESSIMISTIC_WRITE)
    @Query("SELECT a FROM Account a WHERE a.accountNumber = :accountNumber")
    Optional<Account> findByAccountNumberForUpdate(
            @Param("accountNumber") String accountNumber
    );

}